# routes/pdf_service.py
from flask import Blueprint, request, send_file, jsonify
from fpdf import FPDF
import io

pdf_bp = Blueprint("pdf", __name__)


def _clean_text(value, fallback=""):
    if not isinstance(value, str):
        return fallback
    stripped = value.strip()
    if not stripped:
        return fallback
    return stripped[:2000]


def generate_pdf_report(title, subtitle, summary, sections=None, footer=None):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, title, ln=True, align="C")

    pdf.set_font("Helvetica", "", 12)
    pdf.cell(0, 10, subtitle, ln=True, align="C")
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 8, summary)

    for section in sections or []:
        heading = _clean_text(section.get("heading"), "Section")
        body = _clean_text(section.get("body"), "")
        if not body:
            continue
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, heading, ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(0, 8, body)

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 8, footer or "Generated by SE Textile AI Dashboard", ln=True, align="C")

    buffer = io.BytesIO()
    pdf.output(buffer)
    buffer.seek(0)
    return buffer


# POST: Generate AI Report as PDF
@pdf_bp.route("/generate", methods=["POST"])
def generate_pdf():
    """Generate a PDF using structured JSON content."""
    try:
        data = request.get_json(silent=True)
        if not isinstance(data, dict):
            return jsonify({"status": "error", "message": "JSON body required"}), 400

        title = _clean_text(data.get("title"), "SE Textile Report")
        subtitle = _clean_text(data.get("subtitle"), "AI Analytics Summary")
        summary = _clean_text(data.get("summary"), "No summary content provided.")

        sections = data.get("sections", [])
        if sections is not None and not isinstance(sections, list):
            return jsonify({"status": "error", "message": "'sections' must be a list"}), 400

        footer = _clean_text(data.get("footer", "")) or None

        pdf_output = generate_pdf_report(title, subtitle, summary, sections, footer)

        return send_file(
            pdf_output,
            mimetype="application/pdf",
            as_attachment=True,
            download_name="report.pdf"
        )

    except Exception as e:
        print("[Error - PDF Generation]", e)
        return jsonify({"status": "error", "message": "Failed to generate PDF."}), 500
