# routes/pdf_service.py
from flask import Blueprint, request, send_file, jsonify
from fpdf import FPDF
import io
import datetime

pdf_bp = Blueprint("pdf", __name__)

class PDFReport(FPDF):
    def __init__(self, title, subtitle):
        super().__init__()
        self.report_title = title
        self.report_subtitle = subtitle

    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, self.report_title, 0, 1, 'C')
        self.set_font('Arial', 'I', 11)
        self.cell(0, 8, self.report_subtitle, 0, 1, 'C')
        self.ln(5)
        self.line(10, 35, 200, 35)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by Textile Saas App AI', 0, 0, 'C')

    def chapter_title(self, label):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(240, 240, 245)
        self.set_text_color(30, 30, 60)
        self.cell(0, 10, label, 0, 1, 'L', 1)
        self.ln(2)
        self.set_text_color(0)

    def chapter_body(self, text):
        self.set_font('Arial', '', 11)
        self.multi_cell(0, 6, text)
        self.ln(4)

    def add_metrics_grid(self, metrics):
        """Draws a 2xN grid of metrics
        metrics: list of dicts {'label': str, 'value': str}
        """
        if not metrics:
            return
            
        self.ln(2)
        col_width = 90
        row_height = 16
        
        # Grid layout
        for i in range(0, len(metrics), 2):
            # Item 1
            self._metric_cell(metrics[i], col_width, row_height)
            
            # Item 2 (if exists)
            if i + 1 < len(metrics):
                self.set_x(self.get_x() + 5) # Spacer
                self._metric_cell(metrics[i+1], col_width, row_height)
            
            self.ln(row_height + 4)
        self.ln(4)

    def _metric_cell(self, metric, w, h):
        x = self.get_x()
        y = self.get_y()
        
        self.set_fill_color(250, 250, 255)
        self.rect(x, y, w, h, 'F')
        self.rect(x, y, w, h, 'D')
        
        self.set_font('Arial', 'B', 9)
        self.set_text_color(100, 100, 100)
        self.set_xy(x + 2, y + 2)
        self.cell(w-4, 5, metric.get('label', ''), 0, 1)
        
        self.set_font('Arial', 'B', 12)
        self.set_text_color(0, 0, 0)
        self.set_xy(x + 2, y + 8)
        self.cell(w-4, 6, metric.get('value', ''), 0, 0)
        
        # Reset position
        self.set_xy(x + w, y)


def _safe_latin1(text):
    """Convert text to latin-1-safe by replacing unsupported characters."""
    if not isinstance(text, str):
        return str(text) if text is not None else ""
        
    replacements = {
        "₹": "Rs. ",
        "\u20b9": "Rs. ",
        "—": "-",
        "–": "-",
        "“": '"',
        "”": '"',
        "’": "'",
        "‘": "'",
        "•": "-",
        "…": "...",
        "\u2013": "-",
        "\u2014": "-",
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)

    # Encode to latin-1, replacing errors with ?
    return text.encode("latin-1", errors="replace").decode("latin-1")


@pdf_bp.route("/generate", methods=["POST"])
def generate_pdf():
    """Generate a PDF using structured JSON content."""
    try:
        data = request.get_json(silent=True)
        if not isinstance(data, dict):
            return jsonify({"status": "error", "message": "JSON body required"}), 400

        title = _safe_latin1(data.get("title", "Shop Insights Report"))
        subtitle = _safe_latin1(data.get("subtitle", datetime.datetime.now().strftime("%B %Y")))
        
        pdf = PDFReport(title, subtitle)
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        
        # 1. Metrics Grid
        metrics = data.get("metrics", [])
        if metrics:
            safe_metrics = [{"label": _safe_latin1(m.get("label")), "value": _safe_latin1(m.get("value"))} for m in metrics]
            pdf.chapter_title("Key Performance Metrics")
            pdf.add_metrics_grid(safe_metrics)
        
        # 2. Summary
        summary = data.get("summary")
        if summary:
            pdf.chapter_title("Executive Summary")
            pdf.chapter_body(_safe_latin1(summary))

        # 3. Sections
        sections = data.get("sections", [])
        for section in sections:
            heading = _safe_latin1(section.get("heading", ""))
            body = _safe_latin1(section.get("body", ""))
            
            if heading:
                pdf.chapter_title(heading)
            if body:
                pdf.chapter_body(body)

        buffer = io.BytesIO()
        out = pdf.output(dest="S")
        if isinstance(out, str):
            out = out.encode("latin-1", errors="replace")
            
        buffer.write(out)
        buffer.seek(0)
        
        filename = f"Report_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.pdf"

        return send_file(
            buffer,
            mimetype="application/pdf",
            as_attachment=True,
            download_name=filename
        )

    except Exception as e:
        print("[Error - PDF Generation]", e)
        return jsonify({"status": "error", "message": "Failed to generate PDF."}), 500


def generate_pdf_report(title, subtitle, summary, sections=None, footer=None):
    """
    Legacy support wrapper for internal PDF generation calls (e.g. from distributor routes).
    Maps old arguments to new PDFReport class.
    """
    try:
        title = _safe_latin1(title)
        subtitle = _safe_latin1(subtitle)
        
        pdf = PDFReport(title, subtitle)
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        
        # Add summary as first section if present
        if summary:
            pdf.chapter_title("Summary")
            pdf.chapter_body(_safe_latin1(summary))

        # Sections
        for section in sections or []:
            heading = _safe_latin1(section.get("heading", ""))
            body = _safe_latin1(section.get("body", ""))
             
            if heading:
                pdf.chapter_title(heading)
            if body:
                pdf.chapter_body(body)
        
        buffer = io.BytesIO()
        out = pdf.output(dest="S")
        
        if isinstance(out, str):
            out = out.encode("latin-1", errors="replace")
            
        buffer.write(out)
        buffer.seek(0)
        return buffer
    except Exception as e:
        print(f"[Legacy PDF Gen Error] {e}")
        return None
